module.exports = {
  preset: '@react-native/jest-preset',
  setupFiles: ['<rootDir>/jest.setup.js'],
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1',
    '^@app$': '<rootDir>/src/app',
    '^@app/(.*)$': '<rootDir>/src/app/$1',
    '^@contracts$': '<rootDir>/src/contracts',
    '^@contracts/(.*)$': '<rootDir>/src/contracts/$1',
    '^@modules$': '<rootDir>/src/modules',
    '^@modules/(.*)$': '<rootDir>/src/modules/$1',
    '^@shared/db/FlashcardRepository$':
      '<rootDir>/src/modules/review/FlashcardRepository.ts',
    '^@shared/db/GrammarBookmarkRepository$':
      '<rootDir>/src/modules/review/GrammarBookmarkRepository.ts',
    '^@shared/api/reviewEventsClient$':
      '<rootDir>/src/modules/review/api/reviewEventsClient.ts',
    '^@shared$': '<rootDir>/src/shared',
    '^@shared/(.*)$': '<rootDir>/src/shared/$1',
    '^@components$': '<rootDir>/src/components',
    '^@components/(.*)$': '<rootDir>/src/components/$1',
    '^@theme$': '<rootDir>/src/theme',
    '^@theme/(.*)$': '<rootDir>/src/theme/$1',
    '^@release$': '<rootDir>/src/release',
    '^@release/(.*)$': '<rootDir>/src/release/$1',
    '^@i18n$': '<rootDir>/src/i18n',
    '^@i18n/(.*)$': '<rootDir>/src/i18n/$1',
    '^@test-support$': '<rootDir>/src/test-support',
    '^@test-support/(.*)$': '<rootDir>/src/test-support/$1',
    '^@features$': '<rootDir>/src/features',
    '^@features/(.*)$': '<rootDir>/src/features/$1',
    '^@ui$': '<rootDir>/src/ui',
    '^@ui/(.*)$': '<rootDir>/src/ui/$1',
    '^@core$': '<rootDir>/src/core',
    '^@core/(.*)$': '<rootDir>/src/core/$1',
    '^@test$': '<rootDir>/src/test',
    '^@test/(.*)$': '<rootDir>/src/test/$1',
  },
};
