import {StyleSheet} from 'react-native';
import type {AppTheme} from '@ui/theme/index';

export function createYouTubeLessonScreenStyles(theme: AppTheme) {
  return StyleSheet.create({
    headerActions: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: theme.spacing.xs,
    },
    headerBtn: {
      borderColor: theme.colors.outlineVariant,
      borderRadius: theme.radius.pill,
      borderWidth: 1,
      paddingHorizontal: theme.spacing.sm,
      paddingVertical: 4,
    },
    headerBtnActive: {
      backgroundColor: theme.colors.accent,
      borderColor: theme.colors.accent,
    },
    playerWrap: {
      backgroundColor: theme.colors.surface,
    },
    playerControls: {
      alignItems: 'center',
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.sm,
      justifyContent: 'center',
      paddingHorizontal: theme.gutter,
      paddingVertical: theme.spacing.sm,
    },
    errorBanner: {
      gap: theme.spacing.xs,
      paddingHorizontal: theme.gutter,
      paddingVertical: theme.spacing.sm,
    },
    saveWarningBanner: {
      gap: theme.spacing.xs,
      paddingHorizontal: theme.gutter,
      paddingVertical: theme.spacing.sm,
    },
    offlineBanner: {
      gap: theme.spacing.xs,
      paddingHorizontal: theme.gutter,
      paddingVertical: theme.spacing.sm,
    },
    bannerTextWrap: {
      gap: theme.spacing.xs / 2,
    },
    bannerActions: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.xs,
      marginTop: theme.spacing.xs,
    },
    adBanner: {
      alignItems: 'center',
      backgroundColor: theme.colors.surfaceHigh,
      justifyContent: 'center',
      paddingHorizontal: theme.gutter,
      paddingVertical: theme.spacing.xs,
    },
    completedBanner: {
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.accent,
      borderRadius: theme.radius.md,
      borderWidth: 1,
      gap: theme.spacing.sm,
      marginHorizontal: theme.gutter,
      marginVertical: theme.spacing.sm,
      padding: theme.spacing.md,
    },
    completedTitle: {
      textAlign: 'center',
    },
    completedButtonsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: theme.spacing.xs,
      justifyContent: 'center',
    },
    list: {
      paddingBottom: theme.spacing.xl,
      paddingHorizontal: theme.gutter,
      paddingTop: theme.spacing.sm,
    },
    miniWrap: {
      bottom: 0,
      left: 0,
      position: 'absolute',
      right: 0,
    },
    notFoundWrap: {
      flex: 1,
      justifyContent: 'center',
      padding: theme.gutter,
    },
    dotsContainer: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 6,
      justifyContent: 'center',
      paddingVertical: theme.spacing.xs,
    },
    dot: {
      backgroundColor: theme.colors.surfaceHigh,
      borderRadius: 3,
      height: 6,
      width: 6,
    },
    dotActive: {
      backgroundColor: theme.colors.accent,
      borderRadius: 4,
      height: 8,
      width: 8,
    },
    backChip: {
      alignSelf: 'center',
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.accent,
      borderRadius: theme.radius.pill,
      borderWidth: 1,
      bottom: theme.spacing.md,
      elevation: 4,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.xs,
      position: 'absolute',
      shadowColor: theme.colors.text.primary,
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.15,
      shadowRadius: 4,
      zIndex: 10,
    },
    toast: {
      alignSelf: 'center',
      backgroundColor: theme.colors.surface,
      borderColor: theme.colors.surfaceHigh,
      borderRadius: theme.radius.pill,
      borderWidth: 1,
      elevation: 6,
      paddingHorizontal: theme.spacing.md,
      paddingVertical: theme.spacing.xs,
      position: 'absolute',
      shadowColor: theme.colors.text.primary,
      shadowOffset: {width: 0, height: 2},
      shadowOpacity: 0.2,
      shadowRadius: 4,
      top: theme.spacing.xs,
      zIndex: 20,
    },
  });
}
