/** Authoritative M4 matrix `testNamePrefix` values backed by Jest titles. */
export const M4_MATRIX_AUTHORITATIVE_TEST_PREFIXES = [
  'M4-M-INV004-TABS-GATE',
  'M4-M-INV004-SWITCH-ROUTES',
  'M4-M-BOOT-SESSION-RESTORE',
  'M4-M-RESTART-AWAITING',
  'M4-M-REFRESH-EXPIRED-AWAITING',
  'M4-M-REFRESH-CONFIRM-INTERLEAVE',
  'M4-M-DOMAIN-AUDIO',
  'M4-M-DOMAIN-YOUTUBE',
  'M4-M-P2-REGRESSION-SMOKE',
] as const;
